<a href="https://colab.research.google.com/github/zuelmaruixin/AndroidReader/blob/main/6000_Q_A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip uninstall bitsandbytes -y
!pip install -U "bitsandbytes>=0.46.1"
!pip install -U transformers datasets peft trl accelerate



import gc
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from trl import SFTTrainer, SFTConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model_id = "Qwen/Qwen3-1.7B"

print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))
print("bf16 supported:", torch.cuda.is_bf16_supported())

assert torch.cuda.is_available(),
assert torch.cuda.is_bf16_supported(),
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
dataset = load_dataset("timdettmers/openassistant-guanaco", split="train")

def extract_first_turn(example):
    text = example["text"]

    try:
        if "### Human:" not in text or "### Assistant:" not in text:
            return {"text": ""}

        text = text.strip()

        human_start = text.find("### Human:")
        assistant_start = text.find("### Assistant:", human_start)

        if human_start == -1 or assistant_start == -1:
            return {"text": ""}

        human_part = text[human_start + len("### Human:"):assistant_start].strip()

        next_human_start = text.find("### Human:", assistant_start + len("### Assistant:"))
        if next_human_start == -1:
            assistant_part = text[assistant_start + len("### Assistant:"):].strip()
        else:
            assistant_part = text[assistant_start + len("### Assistant:"):next_human_start].strip()

        if not human_part or not assistant_part:
            return {"text": ""}

        bad_markers = ["### Human:", "### Assistant:"]
        if any(marker in human_part for marker in bad_markers):
            return {"text": ""}
        if any(marker in assistant_part for marker in bad_markers):
            return {"text": ""}

        backward_text = (
            f"以下是一段 AI 的回答:\n{assistant_part}\n\n"
            f"请推断出引发上述回答的用户指令(Instruction):\n{human_part}"
        )
        return {"text": backward_text}

    except Exception:
        return {"text": ""}

print("构建反向数据集...")
backward_dataset = dataset.map(extract_first_turn).filter(lambda x: len(x["text"]) > 0)

split_ds = backward_dataset.train_test_split(test_size=0.1, seed=42)
train_data = split_ds["train"]
eval_data = split_ds["test"]

print("train size:", len(train_data))
print("eval size:", len(eval_data))
print("\n样例：\n")
print(train_data[0]["text"][:1000])
try:
    del model, trainer
except:
    pass
gc.collect()
torch.cuda.empty_cache()
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
model = prepare_model_for_kbit_training(model)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
model.config.use_cache = False
training_args = SFTConfig(
    output_dir="./qwen3_backward_lora",
    dataset_text_field="text",
    max_length=512,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,

    learning_rate=2e-4,
    max_steps=100,
    logging_steps=5,

    eval_strategy="steps",
    eval_steps=20,
    save_strategy="steps",
    save_steps=20,
    load_best_model_at_end=True,

    bf16=True,
    fp16=False,
    bf16_full_eval=True,
    fp16_full_eval=False,

    optim="paged_adamw_8bit",
    gradient_checkpointing=True,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_data,
    eval_dataset=eval_data,
    args=training_args,
    processing_class=tokenizer,
)
trainer.train()
save_path = "./qwen3_backward_lora_adapter"
trainer.model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print(f"LoRA adapter 已保存到: {save_path}")

WARNING: Skipping bitsandbytes as it is not installed.
Collecting bitsandbytes>=0.46.1
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes>=0.46.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes>=0.46.1) (1.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes>=0.46.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes>=0.46.1) (3.0.3)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 18.7 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.2
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Collecting trl
  Downloading trl-1.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 57.9 MB/s eta 0:00:00
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 48.1 MB/s eta 0:00:00
Downloading trl-1.0.0-py3-none-any.whl (630 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.8/630.8 kB 53.1 MB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 55.1 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, transformers, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed datasets-4.8.4 pyarrow-23.0.1 transformers-5.5.0 trl-1.0.0
CUDA available: True
Device: NVIDIA A100-SXM4-80GB
bf16 supported: True

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

README.md:   0%|          | 0.00/395 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

openassistant_best_replies_train.jsonl:   0%|          | 0.00/20.9M [00:00<?, ?B/s]

openassistant_best_replies_eval.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/9846 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/518 [00:00<?, ? examples/s]

构建反向数据集...

Map:   0%|          | 0/9846 [00:00<?, ? examples/s]

Filter:   0%|          | 0/9846 [00:00<?, ? examples/s]

train size: 8861
eval size: 985

样例：

以下是一段 AI 的回答:
Here's a sample code for a React functional component with two divs that have items inside of them. The items are obtained from an array and each item can be dragged and dropped between the two divs:

'''javascript
import React, { useState } from "react";

const App = () => {
  const [list1, setList1] = useState([
    { id: 1, text: "Item 1" },
    { id: 2, text: "Item 2" },
    { id: 3, text: "Item 3" }
  ]);
  const [list2, setList2] = useState([
    { id: 4, text: "Item 4" },
    { id: 5, text: "Item 5" }
  ]);

  const onDragStart = (event, source) => {
    event.dataTransfer.setData("source", source);
  };

  const onDrop = (event, target) => {
    const source = event.dataTransfer.getData("source");
    const sourceList = source === "list1" ? list1 : list2;
    const targetList = target === "list1" ? list1 : list2;
    const item = sourceList.find(i => i.id === Number(event.dataTransfer.getData("id")));

    setList1(source === "list1" && target === "list2" ? source

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

trainable params: 3,211,264 || all params: 1,723,786,240 || trainable%: 0.1863

Adding EOS to train dataset:   0%|          | 0/8861 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/8861 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/985 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/985 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

LoRA adapter 已保存到: ./qwen3_backward_lora_adapter

In [3]:
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
trainer.model.push_to_hub("xinxinwanshishunli/qwen3-backward-lora")
tokenizer.push_to_hub("xinxinwanshishunli/qwen3-backward-lora")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  10%|9         | 1.25MB / 12.9MB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp_48hpdp3/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

CommitInfo(commit_url='https://huggingface.co/xinxinwanshishunli/qwen3-backward-lora/commit/c975ab79658d923c8ca7f4741599643f54faae14', commit_message='Upload tokenizer', commit_description='', oid='c975ab79658d923c8ca7f4741599643f54faae14', pr_url=None, repo_url=RepoUrl('https://huggingface.co/xinxinwanshishunli/qwen3-backward-lora', endpoint='https://huggingface.co', repo_type='model', repo_id='xinxinwanshishunli/qwen3-backward-lora'), pr_revision=None, pr_num=None)

In [8]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

model_id = "Qwen/Qwen3-1.7B"
adapter_path = "./qwen3_backward_lora_adapter"

tokenizer = AutoTokenizer.from_pretrained(adapter_path, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
)

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(base_model, adapter_path)
model.eval()

test_responses = [
    "The capital of Japan is Tokyo.",
    "Monopsony refers to a market structure in which there is only one buyer in a market.",
    "To improve sleep quality, you should maintain a consistent bedtime, avoid caffeine late in the day, and reduce screen exposure before bed.",
    "Here are three ways to reduce stress: exercise regularly, practice mindfulness, and get enough sleep.",
    "Python is a high-level programming language known for its readability and wide range of applications, including web development, data science, and automation."
]

for i, test_response in enumerate(test_responses, 1):
    prompt = f"""以下是一段 AI 的回答:
{test_response}

请推断出引发上述回答的用户指令(Instruction):
"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"\n===== Example {i} =====")
    print(result)

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

===== Example 1 =====
以下是一段 AI 的回答:
The capital of Japan is Tokyo.

请推断出引发上述回答的用户指令(Instruction):
What is the capital of Japan?

===== Example 2 =====
以下是一段 AI 的回答:
Monopsony refers to a market structure in which there is only one buyer in a market.

请推断出引发上述回答的用户指令(Instruction):
What is a monopsony?

===== Example 3 =====
以下是一段 AI 的回答:
To improve sleep quality, you should maintain a consistent bedtime, avoid caffeine late in the day, and reduce screen exposure before bed.

请推断出引发上述回答的用户指令(Instruction):
What are some ways to improve sleep quality?

===== Example 4 =====
以下是一段 AI 的回答:
Here are three ways to reduce stress: exercise regularly, practice mindfulness, and get enough sleep.

请推断出引发上述回答的用户指令(Instruction):
What are three ways to reduce stress?

===== Example 5 =====
以下是一段 AI 的回答:
Python is a high-level programming language known for its readability and wide range of applications, including web development, data science, and automation.

请推断出引发上述回答的用户指令(Instruction):
What is Python?

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
!cp -r /content/qwen3_backward_lora_adapter /content/drive/MyDrive/

print("文件夹已成功复制到 Google Drive 根目录！")

文件夹已成功复制到 Google Drive 根目录！

In [2]:
# !pip uninstall bitsandbytes -y
# !pip install -U "bitsandbytes>=0.46.1"
# !pip install -U transformers datasets peft trl accelerate
# !pip uninstall -y datasets
# !pip install "datasets<4.0.0"
import torch
from google.colab import drive
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
from datasets import load_dataset
import random
import pandas as pd
drive.mount('/content/drive')
model_id = "Qwen/Qwen3-1.7B"
adapter_path = "/content/drive/MyDrive/qwen3_backward_lora_adapter"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    bnb_4bit_quant_type="nf4"
)
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)
print("正在从云盘加载反向模型适配器...")
model = PeftModel.from_pretrained(base_model, adapter_path)
model.eval()
print("正在加载并过滤 LIMA 数据集...")
lima = load_dataset("GAIR/lima", split="train",trust_remote_code=True)
single_turn_lima = lima.filter(lambda x: len(x["conversations"]) == 2)

random.seed(42)
indices = random.sample(range(len(single_turn_lima)), 150)
sampled_data = single_turn_lima.select(indices)
generated_data = []
print("开始生成指令...")
for i, ex in enumerate(sampled_data):
    original_instruction = ex["conversations"][0]
    response = ex["conversations"][1]
    prompt = f"以下是一段 AI 的回答:\n{response}\n\n请推断出引发上述回答的用户指令(Instruction):\n"
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=128,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
    input_len = inputs["input_ids"].shape[1]
    generated_ids = outputs[0][input_len:]
    generated_instruction = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()
    generated_data.append({
        "generated_instruction": generated_instruction,
        "response": response,
        "original_instruction": original_instruction
    })

    if (i + 1) % 10 == 0:
        print(f"进度: {i + 1}/150")

generated_data = [
    x for x in generated_data
    if x["generated_instruction"] and len(x["generated_instruction"].strip()) > 3
]

print("\n--- 生成示例展示 ---")
for i in range(5):
    print(f"示例 {i+1}:")
    print(f"生成的指令: {generated_data[i]['generated_instruction']}")
    print(f"原始回答: {generated_data[i]['response'][:100]}...\n")

df = pd.DataFrame(generated_data)
df.to_json("self_augmentation_results.jsonl", orient="records", lines=True)
!cp self_augmentation_results.jsonl /content/drive/MyDrive/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

正在从云盘加载反向模型适配器...
正在加载并过滤 LIMA 数据集...

plain_text/train/0000.parquet:   0%|          | 0.00/1.68M [00:00<?, ?B/s]

plain_text/test/0000.parquet:   0%|          | 0.00/27.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1030 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/300 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1030 [00:00<?, ? examples/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

开始生成指令...
进度: 10/150
进度: 20/150
进度: 30/150
进度: 40/150
进度: 50/150
进度: 60/150
进度: 70/150
进度: 80/150
进度: 90/150
进度: 100/150
进度: 110/150
进度: 120/150
进度: 130/150
进度: 140/150
进度: 150/150

--- 生成示例展示 ---
示例 1:
生成的指令: advice-giver is trying to manipulate you, you can either ignore them or confront them directly. If they are trying to manipulate you, you can say something like, "I don't want to hear anything else from you. I'm going to take my own advice and do it on my own." If they are trying to help you, you can say something like, "Thank you for your advice. I'm going to take it into consideration and do my best to handle this on my own."

## Politely shut down the conversation

1. Politely decline. If you are not interested in the advice, you can politely decline it
原始回答: When someone gives you unsolicited advice, it can be tricky to know how to respond, no matter how we...

示例 2:
生成的指令: What is the difference between using prop() and attr() when enabling or disabling elements in jQuery?
原始回答: Always use the ```prop()``` method to enable or disable elements when using jQuery (see below for wh...

示例 3:
生成的指令: I have a MySQL container running in Docker. I want to connect to it from MySQL Workbench. I have to change the host to 0.0.0.0. How to do it?
原始回答: By default after deployment MySQL has following connection restrictions:
```mysql> select host, user...

示例 4:
生成的指令: How do I clean slate?
原始回答: Slate is a stone that brings natural beauty into the home, and can be expensive to install. Regular ...

示例 5:
生成的指令: What is the purpose of the | symbol in bash?
原始回答: You are using ```|``` (pipe) to direct the output of a command into another command. What you are lo...

In [2]:
import re
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
INPUT_FILE = "self_augmentation_results.jsonl"
SCORED_OUTPUT_FILE = "self_curation_scored_v3.jsonl"
CURATED_OUTPUT_FILE = "self_curation_high_quality_v3.jsonl"

MODEL_ID = "Qwen/Qwen3-1.7B"
df = pd.read_json(INPUT_FILE, lines=True)

if "generated_instruction" in df.columns and "instruction" not in df.columns:
    df["instruction"] = df["generated_instruction"]

keep_cols = [c for c in ["instruction", "response", "original_instruction"] if c in df.columns]
df = df[keep_cols].copy()

print("原始样本数:", len(df))
print(df.head(3))
def basic_filter(row):
    instr = str(row["instruction"]).strip()
    resp = str(row["response"]).strip()

    bad_phrases = [
        "请推断出引发上述回答",
        "Instruction):",
        "### Human:",
        "### Assistant:",
        "## ",
        "</Reason>",
        "</Score>",
        "Reason:",
        "Score:"
    ]

    if not instr or not resp:
        return False
    if len(instr) < 5 or len(resp) < 5:
        return False
    if len(instr) > 300:
        return False
    if len(resp) > 5000:
        return False
    if "\n\n" in instr:
        return False
    if instr.count("\n") > 1:
        return False
    if any(x in instr for x in bad_phrases):
        return False
    return True

df = df[df.apply(basic_filter, axis=1)].reset_index(drop=True)

print("\n清洗后样本数:", len(df))
print(df.head(3))
print("\n加载 Judge 模型（bf16）...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
# 关键：decoder-only 模型批量推理必须左填充
tokenizer.padding_side = "left"

judge_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    device_map="auto",
    trust_remote_code=True,
)

judge_model.eval()

print("Judge 模型加载完成。")
print("padding_side =", tokenizer.padding_side)
print("bf16 supported =", torch.cuda.is_bf16_supported())

# =========================
# 构造评分 prompt
# 不再让模型自由输出长文本，只让它输出 1~5
# =========================
SYSTEM_PROMPT = """You are an expert evaluator for instruction-response quality.

Evaluate whether the instruction-response pair is a high-quality example for instruction tuning.

Scoring rubric:
1 = Bad. Nonsensical, corrupted, or clearly mismatched.
2 = Poor. Weakly related, unnatural, or incomplete.
3 = Acceptable. Somewhat related, but vague or only partially aligned.
4 = Good. Mostly clear and well-matched, with minor issues.
5 = Excellent. Natural instruction, strong match, and helpful response.

Output only one digit: 1, 2, 3, 4, or 5.
"""

FEW_SHOTS = """Example 1
Instruction: What is the capital of Japan?
Response: The capital of Japan is Tokyo.
Score: 5

Example 2
Instruction: What is the purpose of the | symbol in bash?
Response: You are using | (pipe) to direct the output of a command into another command.
Score: 5

Example 3
Instruction: How do I clean slate?
Response: Slate is a stone that brings natural beauty into the home, and can be expensive to install. Regular maintenance is important.
Score: 2

Example 4
Instruction: advice-giver is trying to manipulate you, you can either ignore them or confront them directly.
Response: When someone gives you unsolicited advice, it can be tricky to know how to respond.
Score: 1
"""

def build_score_prompt(instruction, response):
    return f"""{SYSTEM_PROMPT}

{FEW_SHOTS}

Now evaluate this pair.

Instruction: {instruction}
Response: {response}
Score:"""

# =========================
# 准备分数字符 token id
# 这里直接做“下一 token 分类”
# =========================
score_token_ids = {}
for s in ["1", "2", "3", "4", "5"]:
    ids = tokenizer.encode(s, add_special_tokens=False)
    print(f"Token ids for {s}: {ids}")
    if len(ids) != 1:
        raise ValueError(f"'{s}' is not a single token for this tokenizer, got {ids}")
    score_token_ids[int(s)] = ids[0]

candidate_scores = sorted(score_token_ids.keys())
candidate_token_ids = [score_token_ids[s] for s in candidate_scores]
@torch.no_grad()
def score_batch(batch_df):
    prompts = [
        build_score_prompt(row["instruction"], row["response"])
        for _, row in batch_df.iterrows()
    ]

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1400
    ).to(judge_model.device)

    outputs = judge_model(**inputs)
    next_token_logits = outputs.logits[:, -1, :]   # [batch, vocab]

    candidate_logits = next_token_logits[:, candidate_token_ids]  # [batch, 5]
    pred_idx = torch.argmax(candidate_logits, dim=-1)             # [batch]
    pred_scores = [candidate_scores[i] for i in pred_idx.tolist()]

    # 记录每个分数的相对“置信度”
    probs = torch.softmax(candidate_logits.float(), dim=-1)
    confs = torch.max(probs, dim=-1).values.tolist()

    result_rows = []
    for i, (_, row) in enumerate(batch_df.iterrows()):
        result = {
            "instruction": row["instruction"],
            "response": row["response"],
            "score": pred_scores[i],
            "score_confidence": confs[i],
        }
        if "original_instruction" in batch_df.columns:
            result["original_instruction"] = row["original_instruction"]
        result_rows.append(result)

    return result_rows
BATCH_SIZE = 32
results = []
print("\n开始评分...")
for start in range(0, len(df), BATCH_SIZE):
    batch_df = df.iloc[start:start+BATCH_SIZE].reset_index(drop=True)
    batch_results = score_batch(batch_df)
    results.extend(batch_results)
    print(f"评分进度: {min(start+BATCH_SIZE, len(df))}/{len(df)}")
scored_df = pd.DataFrame(results)
print("\n评分完成。")
print("\n分数分布：")
print(scored_df["score"].value_counts(dropna=False).sort_index())
high_df = scored_df[scored_df["score"] >= 4].reset_index(drop=True)
mid_df  = scored_df[scored_df["score"] == 3].reset_index(drop=True)
low_df  = scored_df[scored_df["score"] <= 2].reset_index(drop=True)

print("\n高质量样本数:", len(high_df))
print("中间样本数:", len(mid_df))
print("低质量样本数:", len(low_df))
curated_df = high_df[["instruction", "response"]].copy()

# =========================
# 给展示用的 10 条生成简短 reason
# =========================
DISPLAY_HIGH_N = min(5, len(high_df))
DISPLAY_LOW_N = min(5, len(low_df))

display_df = pd.concat([
    high_df.head(DISPLAY_HIGH_N),
    low_df.head(DISPLAY_LOW_N)
], axis=0).reset_index(drop=True)

REASON_PROMPT = """You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: {instruction}
Response: {response}
Score: {score}

Reason:"""

@torch.no_grad()
def generate_reason_batch(batch_df):
    prompts = [
        REASON_PROMPT.format(
            instruction=row["instruction"],
            response=row["response"],
            score=row["score"]
        )
        for _, row in batch_df.iterrows()
    ]

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1200
    ).to(judge_model.device)

    outputs = judge_model.generate(
        **inputs,
        max_new_tokens=24,
        do_sample=False,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

    reasons = []
    for i in range(len(prompts)):
        input_len = inputs["attention_mask"][i].sum().item()
        gen_ids = outputs[i][input_len:]
        reason = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()
        reasons.append(reason)
    return reasons

display_reasons = []
if len(display_df) > 0:
    for start in range(0, len(display_df), 8):
        batch_df = display_df.iloc[start:start+8].reset_index(drop=True)
        display_reasons.extend(generate_reason_batch(batch_df))

display_df["reason"] = display_reasons

print("\n================ HIGH QUALITY EXAMPLES ================\n")
for i in range(DISPLAY_HIGH_N):
    row = display_df.iloc[i]
    print(f"[High {i+1}]")
    print("Instruction:", row["instruction"])
    print("Response:", row["response"][:300], "...")
    print("Score:", row["score"], "| Confidence:", round(row["score_confidence"], 4))
    print("Reason:", row["reason"])
    print()

print("\n================ LOW QUALITY EXAMPLES ================\n")
for i in range(DISPLAY_HIGH_N, DISPLAY_HIGH_N + DISPLAY_LOW_N):
    row = display_df.iloc[i]
    print(f"[Low {i - DISPLAY_HIGH_N + 1}]")
    print("Instruction:", row["instruction"])
    print("Response:", row["response"][:300], "...")
    print("Score:", row["score"], "| Confidence:", round(row["score_confidence"], 4))
    print("Reason:", row["reason"])
    print()
scored_df.to_json(SCORED_OUTPUT_FILE, orient="records", lines=True)
curated_df.to_json(CURATED_OUTPUT_FILE, orient="records", lines=True)

print("\n已保存:")
print("-", SCORED_OUTPUT_FILE)
print("-", CURATED_OUTPUT_FILE)
!cp {SCORED_OUTPUT_FILE} /content/drive/MyDrive/
!cp {CURATED_OUTPUT_FILE} /content/drive/MyDrive/

原始样本数: 150
                                         instruction  \
0  advice-giver is trying to manipulate you, you ...
1  What is the difference between using prop() an...
2  I have a MySQL container running in Docker. I ...

                                            response  \
0  When someone gives you unsolicited advice, it ...
1  Always use the ```prop()``` method to enable o...
2  By default after deployment MySQL has followin...

                                original_instruction
0              How to respond to unsolicited advice?
1  I have to disable inputs at first and then on ...
2  How to connect mysql workbench to running mysq...

清洗后样本数: 103
                                         instruction  \
0  What is the difference between using prop() an...
1  I have a MySQL container running in Docker. I ...
2                              How do I clean slate?

                                            response  \
0  Always use the ```prop()``` method to enable o...
1  By default after deployment MySQL has followin...
2  Slate is a stone that brings natural beauty in...

                                original_instruction
0  I have to disable inputs at first and then on ...
1  How to connect mysql workbench to running mysq...
2                                How to clean slate?

加载 Judge 模型（bf16）...

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

Judge 模型加载完成。
padding_side = left
bf16 supported = True
Token ids for 1: [16]
Token ids for 2: [17]
Token ids for 3: [18]
Token ids for 4: [19]
Token ids for 5: [20]

开始评分...
评分进度: 32/103
评分进度: 64/103
评分进度: 96/103
评分进度: 103/103

评分完成。

分数分布：
score
1    31
2     8
3    16
4    37
5    11
Name: count, dtype: int64

高质量样本数: 48
中间样本数: 16
低质量样本数: 39

================ HIGH QUALITY EXAMPLES ================

[High 1]
Instruction: What is the difference between using prop() and attr() when enabling or disabling elements in jQuery?
Response: Always use the ```prop()``` method to enable or disable elements when using jQuery (see below for why).
In your case, it would be:
```$(&quot;#edit&quot;).click(function(event){
   event.preventDefault();
   $('.inputDisabled').prop(&quot;disabled&quot;, false); // Element(s) are now enabled.
});
`` ...
Score: 5 | Confidence: 0.7066
Reason: checked``` property of a checkbox. The ```.prop()``` method
should be used to set ```disabled``` and ```checked``` instead of the ```.attr()```
method. The ```.val()``` method should be used for getting and setting
```value```.&quot; - jQuery documentation for prop()

Pre-jQuery 3.0 (before 2016)
The reason why you should use ```prop``` over ```removeAttr()``` is that ```removeAttr()``` completely removes the ```disabled``` attribute itself - as this method would simply set the corresponding property name to ```false```:

Prior to jQuery 3.0, using .removeAttr() on a boolean attribute such
as checked, selected, or readonly would also set the corresponding
named property to false. This behavior was required for ancient
versions of Internet Explorer but is not correct for modern browsers
because the attribute represents the initial value and the property
represents the current (dynamic) value. - jQuery 3.0 Breaking Changes

While ```prop()``` merely sets the property's underlying boolean value to false.
Score: 5

Reason: The response correctly identifies the key difference between prop() and attr() in the context of enabling/disabling elements in jQuery.

[High 2]
Instruction: What is the security concern of unlocking the bootloader of an Android device?
Response: It's a security concern. The Android documentation doesn't provide a lot of elaboration, stating simply:

  The procedure must be confirmed on-screen, and deletes the user data for privacy reasons.

However, the privacy concern is relatively straightforward to extrapolate. Once the bootloader is unl ...
Score: 4 | Confidence: 0.6914
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: What is the security concern of unlocking the bootloader of an Android device?
Response: It's a security concern. The Android documentation doesn't provide a lot of elaboration, stating simply:

  The procedure must be confirmed on-screen, and deletes the user data for privacy reasons.

However, the privacy concern is relatively straightforward to extrapolate. Once the bootloader is unlocked, the device can be flashed with unsigned images. This means that it is relatively trivial to root the device, and there are actually multiple ways it can be done, such as:

* Flashing a system image with root tools built in
* Flashing a boot image that runs ```adbd``` with root by default (an "unsecure" image)
* Flashing a recovery image, then using that to overwrite the system or boot partitions with ones that allow root access

Once root is obtained, all of the information on ```/data``` essentially becomes accessible. This could be emails, contact information, or many other pieces of personal information that you likely don't want in the wrong hands.

Therefore, it makes sense to wipe all of this data during the unlocking procedure to ensure that there is no off-the-shelf "official" way of bypassing the sandboxing restrictions implemented by the Android operating system, which would thereby allow someone to steal personal data.

Of course, there may be ways to root without wiping on some devices, but they rely on exploits rather than official methods like a bootloader unlock, meaning they are basically bugs.
Score: 4

Reason: The response is comprehensive and provides a detailed explanation of the security concerns related to unlocking the Android bootloader. It covers the potential

[High 3]
Instruction: What is rooting an Android system?
Response: In few words, rooting an Android system means overcome the limitations that were imposed over it by the manufacturer. People may want that for different reasons, but the main one is freedom. Having a rooted phone means you've got all the control over your device.

The main reason people root phones  ...
Score: 4 | Confidence: 0.6455
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: What is rooting an Android system?
Response: In few words, rooting an Android system means overcome the limitations that were imposed over it by the manufacturer. People may want that for different reasons, but the main one is freedom. Having a rooted phone means you've got all the control over your device.

The main reason people root phones is to install a custom ROM. Custom ROMs are often known for improvements in performance and exclusive features that are not present on manufacturer ROMs, like installing apps on sdcard or taking screenshots. Custom ROMS can also become a system update alternative for those devices that were abandoned by their manufacturers. You can see a review of popular ROMS, as an example, here.

Rooting Android also allows you to uninstall stock apps that you don't use or don't want, besides those that violates user's privacy (see CarrierIQ). Another main reason for doing that is to gain more space on internal storage. A rooted device lets you install almost any app that requires root access. Those apps generally aim to do something that would not be possible without that privilege. A lot of useful apps were shown on the previous answer, but you may find a lot more available on Google Play. You can find a list of good apps here.
Score: 4

Reason: The response is accurate and provides a clear explanation of what rooting an Android system is. It covers the main reasons people root

[High 4]
Instruction: What is the difference between list.sort() and sorted() in Python?
Response: Python provides two ways to sort a list, the built-in list method `list.sort()` and the built-in function `sorted()`.

The primary difference between the two is that list.sort() will sort the list in-place, mutating its indexes and returning None, whereas sorted() will return a new sorted list leavi ...
Score: 4 | Confidence: 0.8447
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: What is the difference between list.sort() and sorted() in Python?
Response: Python provides two ways to sort a list, the built-in list method `list.sort()` and the built-in function `sorted()`.

The primary difference between the two is that list.sort() will sort the list in-place, mutating its indexes and returning None, whereas sorted() will return a new sorted list leaving the original list unchanged. Another difference is that sorted() accepts any iterable while list.sort() is a method of the list class and can only be used with lists.

Here is an example of using `list.sort()`:

```
# the list to be sorted
x = [2, 3, 1, 5, 6, 4, 8]

# sort by list.sort()
x.sort()
print(x)
```

The output of the above code is
```
[1, 2, 3, 4, 5, 6, 7, 8]
```

Equivalently, you can use `sorted()`:

```
sorted_x = sorted(x)
```
Score: 4

Reason: The response correctly identifies the key differences between list.sort() and sorted() in Python, including their in-place vs. return

[High 5]
Instruction: How can I learn to play the guitar?
Response: There are several ways to learn how to play the guitar, including:

* Taking lessons from a teacher who can help you learn and give personalized tips based on your level.
* Using online videos and tutorials that offer free lessons and exercises for beginners.
* Practicing independently using books  ...
Score: 4 | Confidence: 0.5933
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: How can I learn to play the guitar?
Response: There are several ways to learn how to play the guitar, including:

* Taking lessons from a teacher who can help you learn and give personalized tips based on your level.
* Using online videos and tutorials that offer free lessons and exercises for beginners.
* Practicing independently using books or websites that teach basic techniques and songs.

It is important to remember that learning to play an instrument takes time and practice, so be patient with yourself and don't get discouraged if you don't see progress right away.
Score: 4

Reason: The response provides a clear and concise explanation of the different methods to learn the guitar, including taking lessons, online resources,


================ LOW QUALITY EXAMPLES ================

[Low 1]
Instruction: I have a MySQL container running in Docker. I want to connect to it from MySQL Workbench. I have to change the host to 0.0.0.0. How to do it?
Response: By default after deployment MySQL has following connection restrictions:
```mysql> select host, user from mysql.user;
+-----------+---------------+
| host      | user          |
+-----------+---------------+
| localhost | healthchecker |
| localhost | mysql.session |
| localhost | mysql.sys     |
|  ...
Score: 2 | Confidence: 0.3779
Reason: .7```

or, if the complete port mapping is required:
```docker run -p 3306:3306 -p 33060:33060 --name=mysql57 -d mysql/mysql-server:5.7
```

* If this is the fresh installation - grab the default password:
```docker logs mysql57 2>&1 | grep GENERATED```
* Connect using ```mysql``` client directly to the mysqld in docker:
```docker exec -it mysql57 mysql -uroot -p```
* If this is the fresh installation you will be asked to change the password using ```ALTER USER``` command. Do it.
* Run SQL:
```update mysql.user set host = '%' where user='root';```
* Quit the ```mysql``` client.
* Restart the container:
```docker restart mysql57```

Now you will be able to connect from MySQL Workbench to
```host: `0.0.0.0`
port: `3306`
```
After all the changes the query will show:
```select host, user from mysql.user;
+-----------+---------------+
| host      | user          |
+-----------+---------------+
| %         | root          |
| localhost | healthchecker |
| localhost | mysql.session |
| localhost | mysql.sys     |
+-----------+---------------+
```
Score: 2

Reason: The response provides a detailed explanation of the default MySQL host restrictions and the steps to change them, but it fails to mention

[Low 2]
Instruction: How do I clean slate?
Response: Slate is a stone that brings natural beauty into the home, and can be expensive to install. Regular maintenance cleaning can help preserve slate. But sometimes, it needs a deep clean or stain removal. A combination of regular cleaning and an occasional deep clean can help keep your slate in good con ...
Score: 2 | Confidence: 0.4936
Reason: The response is too long and includes unnecessary information. The user asked for a simple explanation of how to clean slate, but

[Low 3]
Instruction: What is the purpose of the | symbol in bash?
Response: You are using ```|``` (pipe) to direct the output of a command into another command. What you are looking for is ```&&``` operator to execute the next command only if the previous one succeeded:
```cp /templates/apple /templates/used && cp /templates/apple /templates/inuse && rm /templates/apple
``` ...
Score: 2 | Confidence: 0.4942
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: What is the purpose of the | symbol in bash?
Response: You are using ```|``` (pipe) to direct the output of a command into another command. What you are looking for is ```&&``` operator to execute the next command only if the previous one succeeded:
```cp /templates/apple /templates/used && cp /templates/apple /templates/inuse && rm /templates/apple
```
Or
```cp /templates/apple /templates/used && mv /templates/apple /templates/inuse
```

To summarize (non-exhaustively) bash's command operators/separators:

* ```|``` pipes (pipelines) the standard output (```stdout```) of one command into the standard input of another one. Note that ```stderr``` still goes into its default destination, whatever that happen to be.
* ```|&```pipes both ```stdout``` and ```stderr``` of one command into the standard input of another one. Very useful, available in bash version 4 and above.
* ```&&``` executes the right-hand command of ```&&``` only if the previous one succeeded.
* ```||``` executes the right-hand command of ```||``` only it the previous one failed.
* ```;``` executes the right-hand command of ```;``` always regardless whether the previous command succeeded or failed. Unless ```set -e``` was previously invoked, which causes ```bash``` to fail on an error.

Score: 2

Reason: The response is correct but not very helpful. It provides a correct explanation of the ```|``` symbol, but it's

[Low 4]
Instruction: What is the correct way to address the Queen of the United Kingdom?
Response: Queens are typically addressed as "Your Majesty," but in modern times there is rarely any enforcement or punishment for getting it wrong. Queen Elizabeth II, the most famous living monarch, has been winked at by a U.S. president, among many other gaffes she's witnessed over the years. The royal fami ...
Score: 2 | Confidence: 0.4983
Reason: The response is not correct. The instruction asks for the correct way to address the Queen of the United Kingdom, but the

[Low 5]
Instruction: What is the difference between R and Mathematica in terms of algorithm support?
Response: Mathematica doesn't have the depth of algorithm support that is present in R or Python. Julia has much more limited algorithm support but does exhibit a good turn of speed.
The few algorithms that Mathematica does support are not particularly well exposed for the type of tweaking needed to win Kaggl ...
Score: 1 | Confidence: 0.4316
Reason: You are an evaluator.
Give one short sentence explaining why this instruction-response pair got the assigned score.

Instruction: What is the difference between R and Mathematica in terms of algorithm support?
Response: Mathematica doesn't have the depth of algorithm support that is present in R or Python. Julia has much more limited algorithm support but does exhibit a good turn of speed.
The few algorithms that Mathematica does support are not particularly well exposed for the type of tweaking needed to win Kaggle competitions.
Mathematica, as of version 10, supports the following classifiers:  "LogisticRegression", "Markov", "NaiveBayes", "NearestNeighbors", "NeuralNetwork", "RandomForest", "SupportVectorMachine".
Whilst it does offer one ensemble method, RandomForest, it lacks both Bagging and any flavour of boosting, such as Adaboost. These latter general ensemble methods allow you to leverage the power of a base classifier, either built-in or, of greater utility when exploring performance improvements, of your own design. This limits significantly the potential for creating novel methods within the existing machine learning framework.
Mathematica's strengths lay with it's expressive, compact, language, strong visualisation capabilities and easy parallelization. These make it very efficient to explore new strategies and combinations of ML algorithms you may already have implemented.
A less often mentioned benefit is that use of Mathematica in a functional programming style tends to lead to fewer bugs in the final code.
Score: 1

Reason: The response is too long and contains a lot of information that is not relevant to the question. The response is not concise


已保存:
- self_curation_scored_v3.jsonl
- self_curation_high_quality_v3.jsonl

In [3]:
import pandas as pd

scored_df = pd.read_json("self_curation_scored_v3.jsonl", lines=True)

curated_df = scored_df[scored_df["score"] >= 4][["instruction", "response"]].drop_duplicates().reset_index(drop=True)

print("最终用于第4步训练的样本数:", len(curated_df))

curated_df.to_json("self_curation_high_quality_final.jsonl", orient="records", lines=True)

最终用于第4步训练的样本数: 48

In [8]:

from datasets import Dataset
from huggingface_hub import login

login()

hf_dataset = Dataset.from_pandas(curated_df)

dataset_repo = "xinxinwanshishunli/self-curated-lima-qwen3"
hf_dataset.push_to_hub(dataset_repo)

print("已推送数据集到 HF:", dataset_repo)

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmplleb9obj.parquet    : 100%|##########| 49.7kB / 49.7kB

已推送数据集到 HF: xinxinwanshishunli/self-curated-lima-qwen3

In [4]:
# !pip install -U transformers datasets peft trl accelerate
import gc
import torch
import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig
MODEL_ID = "Qwen/Qwen3-1.7B"
INPUT_FILE = "self_curation_high_quality_final.jsonl"
OUTPUT_DIR = "./qwen3_forward_lora"
SAVE_PATH = "./qwen3_forward_lora_adapter"

print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))
print("bf16 supported:", torch.cuda.is_bf16_supported())
df = pd.read_json(INPUT_FILE, lines=True)
df = df[["instruction", "response"]].dropna().drop_duplicates().reset_index(drop=True)

print("最终训练样本数:", len(df))
print(df.head(3))
dataset = Dataset.from_pandas(df)
split_ds = dataset.train_test_split(test_size=0.1, seed=42)
train_data = split_ds["train"]
eval_data = split_ds["test"]

print("train size:", len(train_data))
print("eval size:", len(eval_data))

def format_forward(example):
    text = (
        f"Instruction:\n{example['instruction']}\n\n"
        f"Response:\n{example['response']}"
    )
    return {"text": text}

train_data = train_data.map(format_forward)
eval_data = eval_data.map(format_forward)

print("\n训练样例：")
print(train_data[0]["text"][:1000])

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"

try:
    del model, trainer
except:
    pass
gc.collect()
torch.cuda.empty_cache()

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    device_map="auto",
    trust_remote_code=True,
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

model.config.use_cache = False
training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    dataset_text_field="text",
    max_length=768,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,

    learning_rate=2e-4,
    num_train_epochs=8,     # 数据很少，多跑几轮
    logging_steps=1,

    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,

    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),

    gradient_checkpointing=True,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_data,
    eval_dataset=eval_data,
    args=training_args,
    processing_class=tokenizer,
)

trainer.train()
trainer.model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"LoRA adapter 已保存到: {SAVE_PATH}")

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.5.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.4)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
CUDA available: True
Device: NVIDIA A100-SXM4-80GB
bf16 supported: True
最终训练样本数: 48
                                         instruction  \
0  What is the difference between using prop() an...
1  What is the security concern of unlocking the ...
2                 What is rooting an Android system?

                                            response
0  Always use the ```prop()``` method to enable o...
1  It's a security concern. The Android documenta...
2  In few words, rooting an Android system means ...
train size: 43
eval size: 5

Map:   0%|          | 0/43 [00:00<?, ? examples/s]

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

训练样例：
Instruction:
What is the implementation of std::function?

Response:
The implementation of ```std::function``` can differ from one implementation to another, but the core idea is that it uses type-erasure. While there are multiple ways of doing it, you can imagine a trivial (not optimal) solution could be like this (simplified for the specific case of ```std::function<int (double)>``` for the sake of simplicity):
```struct callable_base {
   virtual int operator()(double d) = 0;
   virtual ~callable_base() {}
};
template <typename F>
struct callable : callable_base {
   F functor;
   callable(F functor) : functor(functor) {}
   virtual int operator()(double d) { return functor(d); }
};
class function_int_double {
   std::unique_ptr<callable_base> c;
public:
   template <typename F>
   function(F f) {
      c.reset(new callable<F>(f));
   }
   int operator()(double d) { return c(d); }
// ...
};
```
In this simple approach the ```function``` object would store just a ```unique_ptr``` to

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

trainable params: 3,211,264 || all params: 1,723,786,240 || trainable%: 0.1863

Adding EOS to train dataset:   0%|          | 0/43 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/43 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/5 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/5 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

LoRA adapter 已保存到: ./qwen3_forward_lora_adapter

In [13]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

MODEL_ID = "Qwen/Qwen3-1.7B"
ADAPTER_PATH = "./qwen3_forward_lora_adapter"

tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    device_map="auto",
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()

test_instructions = [
    "What is the difference between list.sort() and sorted() in Python?",
    "How can I learn to play the guitar?",
    "What is rooting an Android system?",
    "What is the security concern of unlocking the bootloader of an Android device?",
    "How can I improve sleep quality?"
]

for i, instr in enumerate(test_instructions, 1):
    prompt = f"Instruction:\n{instr}\n\nResponse:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=92,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.15,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    input_len = inputs["input_ids"].shape[1]
    gen_ids = outputs[0][input_len:]
    response = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()

    print("=" * 80)
    print(f"Example {i}")
    print("Instruction:", instr)
    print("Response:", response)

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

================================================================================
Example 1
Instruction: What is the difference between list.sort() and sorted() in Python?
Response: In this case, we will compare the two methods of sorting lists. The first method is to sort a list directly with the built-in .sort() function while the second one is to return an ordered version of it via the sorted() function.

When you call .sort(), any changes made on your original list are permanent. On the other hand, when using sorted(), the new variable that contains the result does not affect anything else as long as it's used
================================================================================
Example 2
Instruction: How can I learn to play the guitar?
Response: To start learning how to play an instrument like the guitar, you'll need some basic tools and materials. You’ll need a few things: strings for your guitar (you will have to choose from different types of string gauges), tuning pegs or tuners that allow you to tune them properly, fretboard markers which help with positioning notes on the neck of the guitar when playing along with other people or in lessons, and maybe even a strap to hold down
================================================================================
Example 3
Instruction: What is rooting an Android system?
Response: Rooting means taking control over your Android phone. Rooted devices are able to do things that non-rooted phones cannot, such as installing custom firmware or modifying the user interface.

There are a number of reasons why someone would want to root their Android device:

- Install third-party apps
- Access and modify system files
- Add features not available out-of-the-box (such as advanced screen mirroring)
- Change settings in ways not possible with standard app
================================================================================
Example 4
Instruction: What is the security concern of unlocking the bootloader of an Android device?
Response: The most common and dangerous thing about unlocking the bootloaders on your Android phone (especially if you're using a custom recovery) is that it allows full access to the file system. This means you can install any app, including apps with malware or rootkits.

A second big problem is that some devices allow users to unlock their bootloader in order to get more RAM by changing their kernel configuration. Unlocking this changes how much memory the processor uses –
================================================================================
Example 5
Instruction: How can I improve sleep quality?
Response: To help you improve your sleep, here are some tips that may work for you:

1. Go to bed and wake up at the same time each day even on weekends.
2. Avoid screens (like phones or tablets) 30 minutes before bedtime.
3. Don't eat heavy meals close to bedtime. Keep a light snack if needed but avoid anything too high in sugar or caffeine
4. Try not to nap during the day - naps should

In [6]:
# !pip install -U huggingface_hub

from huggingface_hub import login
login()

repo_name = "xinxinwanshishunli/qwen3-forward-lora-self-alignment"

trainer.model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

print("已推送到 HF:", repo_name)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   4%|4         |  578kB / 12.9MB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpvmlga50l/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

已推送到 HF: xinxinwanshishunli/qwen3-forward-lora-self-alignment